#!/usr/bin/env bash
# Do an adb operation with a file, pull it, and remove it.
#
# Dependencies: adb
# Author: metakirby5

checkdep() {
  type "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep adb)"
if [ "$missing" ]; then
  echo "The following dependencies are missing:$missing"
  exit 1
fi

usage() {
  echo "Usage: $(basename "$0") [filename] [commands...]"
  exit 1
}

[ "$#" -lt 2 ] && usage

filename="/sdcard/$1"
shift

finish() {
  sleep 0.5
  adb pull "$filename"
  adb shell rm "$filename"
}
trap finish EXIT

adb shell "$@" "$filename"
