#!/usr/bin/env bash
# Add album art to currently playing in mpd.
#
# Author: metakirby5

usage() {
  echo "USAGE: $(basename "$0") [image file]"
  exit 1
}

# Sanity checks
[ "$#" -ne 1 ] && usage

add-art -i "$1" "${XDG_MUSIC_DIR%%/}/$(mpc current --format '%file%')"

