#!/usr/bin/env bash
# Gentle encouragement with anime, brought to you by 1339.cf.

ANIME="$(mktemp).png"
ANIME_WIDTH="250"

curl -sfL "http://1339.cf/grill.php" -o "$ANIME"
convert "$ANIME" -resize "$ANIME_WIDTH" "$ANIME"
notify-send -i "$ANIME" -a "1339.cf" "頑張れ！"

