#!/usr/bin/env bash
# Reinstalls an apk.
#
# Dependencies: adb

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep adb)"
if [ "$missing" ]; then
  echo "The following dependencies are missing:$missing"
  exit 1
fi

usage() {
  echo "Usage: $(basename "$0") [filename] [args...]"
  exit 1
}

[ "$#" -lt 1 ] && usage

echo "Attempting install..."
adb install -r -d "$@"
