#!/usr/bin/env bash
# Reinstalls an apk.
#
# Dependencies: adb

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep adb)"
if [ "$missing" ]; then
  echo "The following dependencies are missing:$missing"
  exit 1
fi

usage() {
  echo "Usage: $(basename "$0") [filename] [args...]"
  exit 1
}

[ "$#" -lt 1 ] && usage

echo "Attempting install..."
PATTERN='.*\[INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install \([^\s]*\) without first uninstalling.\].*'
out="$(command adb install "$@" 2>&1)"
pkg="$(sed -n "s/$PATTERN/\1/p" <<< "$out")"
if [ "$pkg" ]; then
  echo "Package detected: $pkg"
  echo "Uninstalling..."
  command adb uninstall "$pkg"
  echo "Reinstalling..."
  command adb install "$@"
else
  echo "$out"
fi
