#!/usr/bin/env bash
# Sends a notification once per 30 seconds if the battery is at or below 15%.

DUNSTIFY_ID="/tmp/bat-notify_dunstify_id"

while true; do
	percent="$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		awk '/percentage/{ gsub(/%/, ""); print $2 }')"

	if [ "$percent" -le 15 ]; then
		# Get the dunstify id
		[ ! -z "$(cat "$DUNSTIFY_ID")" ] && id_arg="-r $(cat "$DUNSTIFY_ID")"

		dunstify \
			-a "bat-notify" \
			-p $id_arg > "$DUNSTIFY_ID" \
			-u C "Battery at ${percent}%!"
	fi

	sleep 30
done
