#!/usr/bin/env bash
# A script to bundle up only leaf brew dependencies.
# Requires Homebrew/homebrew-bundle.

brew bundle dump --file=- |\
  grep -Ff <(cat <(brew leaves) <(echo 'tap'; echo 'cask'))
