#!/usr/bin/env bash
# A script to prune the leaves of your brew packages.
# Requires beeftornado/homebrew-rmtree

for formula in $(brew leaves); do
  read -p "Keep $(brew desc "$formula")? [Y/n] " keep
  case $keep in
    [Nn])
      echo "    Uninstalling ${formula}..."
      brew rmtree "$formula"
      ;;
    *)
      echo "    Keeping ${formula}..."
      ;;
  esac
done
