#!/usr/bin/env bash
# Unintalls bloatware from the Fossil Sport smartwatch.

apps=(
  com.amberweather.watch
  com.dianping.v1
  com.eg.android.AlipayGphone
  com.fossil.charge.darter
  com.fossil.wearables.ds
  com.fossil.wearables.ks
  com.fossil.wearables.mk
  com.fossil.wearables.ms
  com.fossil.wearables.pu
  com.google.android.inputmethod.pinyin
  com.gotokeep.androidwear
  com.mobvoi.ticwear.aw.appstore
  com.mobvoi.ticwear.sidewearvoicesearch
  com.mobvoi.wear.account.aw
  com.mobvoi.wear.appsservice
  com.mobvoi.wear.fitness.aw
  com.mobvoi.wear.health.aw
  com.mobvoi.wear.neteasemusic.aw
  com.mobvoi.wear.social.aw
  com.nike.plusgps
  com.safetrekapp.safetrek
  com.sdu.didi.psnger
  com.sogou.map.android.maps
  com.spotify.music
  ctrip.android.view
)

pm() {
  adb shell pm "$@"
}

for app in ${apps[@]}; do
  echo "=== $app"
  echo "Uninstall: $(pm uninstall --user 0 "$app")"
  echo "Disable: $(pm disable-user --user 0 "$app" 2>/dev/null || echo "Skipped")"
done
