#!/usr/bin/env bash
# Get the currently focused window's title, truncated to 40 characters.
# https://maxammann.github.io/2015/03/07/conky-window-title/

xprop -id \
$(xprop -root _NET_ACTIVE_WINDOW | cut -d\  -f5) _NET_WM_NAME |\
awk -v len=100 '
  {
    gsub(/^.* = "|"$|\\/, "", $0)
    if (length($0) > len)
      print substr($0, 0, len-1) "…"
    else
      print $0
  }
'

