#!/usr/bin/env bash
# Monitors a gitlab job for completion: failed, success, or canceled.
# Checks every minute.
# API calls inferred from repo information.
#
# Dependencies: gitlab-api, git, urlencode, curl, jq
# Environment variables: $GITLAB_TOKEN
#
# Usage: gitlab-job-monitor [job id]
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="\
$(checkdep gitlab-api)\
$(checkdep git)\
$(checkdep urlencode)\
$(checkdep curl)\
$(checkdep jq)\
"
[ "$missing" ] && "The following dependencies are missing:$missing"

usage() {
  echo "Usage: ${0##*/} [job id]"
  echo
  exit 1
}

[ "$#" -ne 1 ] && usage

call() {
  gitlab-api "$@" 2>/dev/null
}

parse() {
  jq -r '.status' 2>/dev/null
}

# Loading spinner: https://unix.stackexchange.com/a/225183
i=1
sp="/-\|"
echo -n 'Monitoring...  '
spin() {
  printf "\b${sp:i++%${#sp}:1}"
}

while :; do
  case "$(call "jobs/$1" | parse)" in
    failed|success|canceled)
      exit 0
      ;;
  esac

  for i in {1..600}; do
    spin
    sleep 0.1
  done
done
