#!/usr/bin/env bash
# Installs an apk found in GitLab job artifacts, e.g.
# https://gitlab.domain.com/user/project/-/jobs/12345
#
# Dependencies: mktemp, unzip, adb, gitlab-artifacts
# Environment variables: $GITLAB_TOKEN
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep mktemp)$(checkdep unzip)$(checkdep adb)$(checkdep gitlab-artifacts)"
[ "$missing" ] && fail "The following dependencies are missing:$missing"
[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'

usage() {
  echo "Usage: $(basename "$0") [job URL] (name pattern) (installer...)"
  echo "  For iOS: $(basename "$0") [job URL] '*.ipa' ideviceinstaller -i"
  exit 1
}

[ "$#" -lt 1 ] && usage

job="$1"; shift
name_pat="$1"; shift

artifacts="$(mktemp).zip"
artifacts_dir="$(mktemp)_extracted"
finish() {
  rm -rf "$artifacts" "$artifacts_dir"
}
trap finish EXIT

gitlab-artifacts "$job" "$artifacts" || exit 1
unzip "$artifacts" -d "$artifacts_dir"
default_cmd=( "adb" "install" "-r" "-d" )
find "$artifacts_dir" -name "${name_pat:-*.apk}" | xargs "${@:-"${default_cmd[@]}"}" || exit 1
