#!/usr/bin/env bash
# Prints a gitlab job ID.
# API calls inferred from repo information.
#
# Dependencies: gitlab-api, git, urlencode, curl, jq, fzf
# Environment variables: $GITLAB_TOKEN, $NO_CACHE
#
# Usage: gitlab-job-id (git ref)
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  type "$1" &>/dev/null || echo " $1"
}

missing="\
$(checkdep gitlab-api)\
$(checkdep git)\
$(checkdep urlencode)\
$(checkdep curl)\
$(checkdep jq)\
$(checkdep fzf)\
"
[ "$missing" ] && fail "The following dependencies are missing:$missing"
[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'

maybe_fail() {
  [ "$?" -ne 0 ] && fail "$@"
}

maybe_exit() {
  [ -z "$1" ] && fail "$2"
}

call() {
  gitlab-api "$@" 2>/dev/null
}

parse() {
  jq -r "$1 // \"\"" 2>/dev/null
}

cache=/tmp/gitlab-job-id
mkdir -p "$cache"

commit="$(git rev-parse --short=8 "${1:-HEAD}")"

# Use cached pipeline info if we can, and cache it if we look it up.
cached="$cache/$commit"
[ -z "$NO_CACHE" ] && pipeline="$(cat "$cached" 2>/dev/null)" ||
  pipeline="$(call "repository/commits/$commit" | parse '.last_pipeline.id')" &&
  <<<"$pipeline" cat > "$cached"

maybe_fail "Pipeline API failed."
maybe_exit "$pipeline" "No pipeline ID for $commit."
log "Pipeline: $pipeline"

jobz="$(call "pipelines/$pipeline/jobs" | parse '.[] | "\(.id)\t\(.status)\t\(.name)"')"
maybe_fail "Jobs API failed."
maybe_exit "$jobz" "No jobs for $pipeline at $commit."

job="$(<<<"$jobz" fzf --prompt 'Job: ')"
maybe_exit "$job" "No job selected."

<<<"$job" cut -f 1
