#!/usr/bin/env bash
# Monitors a gitlab job for completion: failed, success, or canceled.
# Checks every 10 seconds.
# API calls inferred from repo information.
#
# Dependencies: gitlab-api, git, urlencode, curl, jq
# Environment variables: $GITLAB_TOKEN
#
# Usage: gitlab-job-monitor [job ids...]
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  type "$1" &>/dev/null || echo " $1"
}

missing="\
$(checkdep gitlab-api)\
$(checkdep git)\
$(checkdep urlencode)\
$(checkdep curl)\
$(checkdep jq)\
"
[ "$missing" ] && fail "The following dependencies are missing:$missing"
[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'

usage() {
  echo "Usage: ${0##*/} [job ids...]"
  echo
  exit 1
}

[ "$#" -lt 1 ] && usage

call() {
  gitlab-api "$@" 2>/dev/null
}

parse() {
  jq -r '.status' 2>/dev/null
}

# Loading spinner: https://unix.stackexchange.com/a/225183
i=1
sp="/-\|"
spin() {
  printf "\b${sp:i++%${#sp}:1}"
}
end_spin() {
  printf "\b$*\n"
}

while [ "$#" -gt 0 ]; do
  job=${1##*/}
  echo -n "Monitoring job ID $job...  "

  while :; do
    job_info="$(call "jobs/$job")" || fail 'Jobs API failed.'
    job_status="$(parse <<<"$job_info")" || fail 'Jobs status parse failed.'

    case "$job_status" in
      failed|success|canceled)
        end_spin "$job_status"
        break
        ;;
      null)
        end_spin 'Response: No job status.'
        echo "$job_info"
        break
        ;;
    esac

    for i in {1..100}; do
      spin
      sleep 0.1
    done
  done

  echo
  shift
done
