#!/usr/bin/env bash
# Calls a gitlab endpoint based on the repo information.
#
# Dependencies: git, urlencode, curl
# Environment variables: $GITLAB_TOKEN
#
# Usage: gitlab-api (endpoint) (curl args)
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  type "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep git)$(checkdep urlencode)$(checkdep curl)"
[ "$missing" ] && fail "The following dependencies are missing:$missing"
[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'

remote="$(git remote get-url --push origin)"
no_user="${remote##*@}"
host="${no_user%%:*}"
project_git="${no_user##*:}"
project="$(urlencode "${project_git%%.*}")"
base="$host/api/v4/projects/$project"

curl -L --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$base/$1" "${@:2}"
