#!/usr/bin/env bash
# Gets artifacts from a GitLab job, e.g.
# https://gitlab.domain.com/user/project/-/jobs/12345
#
# Dependencies: urlencode, curl
# Environment variables: $GITLAB_TOKEN
#
# Author: metakirby5

log() {
  echo "$@" >/dev/stderr
}

fail() {
  log "$@"
  exit 1
}

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep urlencode)$(checkdep curl)"
[ "$missing" ] && fail "The following dependencies are missing:$missing"
[ -z "$GITLAB_TOKEN" ] && fail 'Missing $GITLAB_TOKEN!'

usage() {
  echo "Usage: $(basename "$0") [job URL] [output filename]"
  exit 1
}

[ "$#" -ne 2 ] && usage

protocol="${1%%://*}"
strip_protocol="${1##*://}"
base="$protocol://${strip_protocol%%/*}"
strip_base="${strip_protocol#*/}"
project="${strip_base%%/-*}"
job="${strip_base##*/}"

endpoint="$base/api/v4/projects/$(urlencode "$project")/jobs/$job/artifacts"
echo "Retrieving: $endpoint"

curl -o "$2" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$endpoint"
