#!/usr/bin/env bash

usage() {
  echo "USAGE: hrdblur [gaussian blur radius] [input file] [outputfile]"
  exit 1
}

[ "$#" -ne 3 ] && usage

convert -gaussian "$1" "$2" - | composite -compose overlay "$2" - "$3"
