#!/usr/bin/env bash
# Pixellated lockscreen.

TMPBG="$(mktemp).png"

scrot "$TMPBG"
mogrify -sample 5% -sample 2000% "$TMPBG"
killall -SIGUSR1 dunst # pause dunst
i3lock -ndui "$TMPBG"
killall -SIGUSR2 dunst # resume dunst
rm "$TMPBG"

