#!/usr/bin/env bash
# Updates nginx letsencrypt domains by server_name.

/opt/letsencrypt/letsencrypt-auto \
  certonly -a webroot --webroot-path=/var/www/ssl \
  $(grep -hro '^\s*server_name\s\+[a-zA-Z0-9.-]\+' /etc/nginx/ |
    awk '{ FS = "\n"; $1 = ""; print $0 }' |
    sort | uniq | xargs printf ' -d %s')
