#!/usr/bin/env bash
# Creates a gif using ffmpeg

usage() {
  echo "USAGE: mkgif [src] [dest] (width)"
  exit 1
}

# Sanity checks
[ "$#" -lt 2 ] && usage

palette="$(mktemp).png"
width="${3:-iw*0.5}"

ffmpeg -i "$1" -vf "fps=10,scale=$width:-1:flags=lanczos,palettegen" \
  "$palette"

ffmpeg -i "$1" -i "$palette" -filter_complex \
  "fps=10,scale=$width:-1:flags=lanczos[x];[x][1:v]paletteuse" \
  -loop 0 "$2"

rm "$palette"
