#!/usr/bin/env bash
# Display album art in term, auto-change on song change
# Note that this will make your cursor invisible. Restore with `tput cnorm`
# metakirby5

CHARHEIGHT=31
CHARWIDTH=15
PAD=0

ALBUM_ART="$(mktemp).png"
NO_ART="$(mktemp).png"
convert -size 1 xc:transparent "$NO_ART"

put_art() {
  rm "$ALBUM_ART" &>/dev/null

  # Get album art
  ffmpeg -y -i "${XDG_MUSIC_DIR%%/}/$(mpc current --format '%file%')" \
    "$ALBUM_ART" 2>/dev/null
}

display_art() {
  local win_width="$(($(tput cols) * $CHARWIDTH))"
  local win_height="$(($(tput lines) * $CHARHEIGHT))"
  local width="$(($win_width - 2 * $PAD))"
  local height="$(($win_height - 2 * $PAD))"
  local size="$(($width < $height ? $width : $height))"
  local x="$((($width - $size) / 2 + $PAD))"
  local y="$((($height - $size) / 2 + $PAD))"

  # Clears the screen
  clear
  printf "0;1;;;$win_width;$win_height;;;;;$NO_ART\n4;\n3;" |\
    /usr/lib/w3m/w3mimgdisplay

  printf "0;1;$x;$y;$size;$size;;;;;$ALBUM_ART\n4;\n3;" |\
    /usr/lib/w3m/w3mimgdisplay
}

# Initial display
clear
tput civis
put_art && display_art

# Connect to socket
exec 3<> /dev/tcp/localhost/6600
last="$(mpc current)"

# Enter message loop
while read -u3 msg; do
  # If we got an OK
  if [[ "$msg" == OK* ]]; then
    # Check if the song changed
    song="$(mpc current)"

    if [[ "$song" != "$last" ]]; then
      put_art
      display_art
    fi

    last="$song"

    # Listen for next change
    echo 'idle player playlist' >&3
  fi
done &

# Also display on screen size change
prev_width="$(tput cols)"
prev_height="$(tput lines)"
while true; do
  width="$(tput cols)"
  height="$(tput lines)"
  [[ "$width" != "$prev_width" || "$height" != "$prev_height" ]] \
    && display_art
  prev_width="$width"
  prev_height="$height"
  sleep 1
done &

# Also display on keypress
while read -rsn1; do
  display_art
done
