#!/usr/bin/env bash

# multitest
# Author: Ethan Chan
# Date: 2/6/14
#
# A script to test multiple input sets and arg sets for coding assignments.

# -o | -e
case "$1" in
	-o)
		flags="$flags -o"
		shift
		;;
	-e)
		flags="$flags -e"
		shift
		;;
esac

# Input sets
while [[ ! -x "$1" && $# -gt 0 ]]; do
    input="$1 $input"
    shift
done

if [[ $# -lt 3 ]]; then
	echo
	echo "tester's all test cases found in provided files, with provided inputs."
	echo "Usage: multitest (-o | -e) (input sets) [local prog] [solution prog] [arg sets]"
	echo "    -o -- only test stdout"
	echo "    -e -- only test stderr"
	echo
	exit 1
fi

make

# Progs
loc=$1
shift
sol=$1
shift

# Arg sets
while [[ $# -gt 0 ]]; do
	if [[ -f $1 ]]; then
		while read line; do
			if [[ `echo $line | grep -v ^//` ]]; then
				if [[ $input ]]; then
					for i in $input; do
						eval "tester$flags $i $loc $sol $line"
					done
				else
					eval "tester$flags $loc $sol $line"
				fi
			fi
		done < $1
	else
		echo
		echo "File $1 not found!"
	fi
	shift
done

echo
