#!/bin/bash

if [[ $# < 4 ]]; then
	echo
	echo "tester's all test cases found in provided files, with provided inputs."
	echo "Usage: multitest [inputs] [local prog] [solution prog] [test case files]"
	echo
	exit 1
fi

while [[ ! -x "$1" ]]; do
    input="$1 $input"
    shift
done

loc=$1
shift
soln=$1
shift

while [[ $# > 0 ]]; do
	if [[ -f $1 ]]; then
		while read line; do
			if [[ `echo $line | grep -v ^//` ]]; then
                for i in $input; do
                    testernovim $i $loc $soln $line
                done
			fi
		done < $1
	else
		echo
		echo "File $1 not found!"
	fi
	shift
done

echo
