#!/bin/bash

# pull-config
# Author: Ethan Chan
# Date: 5/5/14
#
# A script to pull my git-maintained configs.

echo

echo "===Pulling ~/bin..."
cd ~/bin
git pull
echo

echo "===Pulling ~/dotfiles..."
cd ~/dotfiles
git pull
echo
