#!/bin/bash

# push-config
# Author: Ethan Chan
# Date: 5/5/14
#
# A script to push my git-maintained configs.

echo

echo "===Pushing ~/bin..."
cd ~/bin
git push
echo

echo "===Pushing ~/dotfiles..."
cd ~/dotfiles
git push
echo
