#!/usr/bin/env bash
# Reload the desktop

killall compton dunst

i3-msg 'restart' &>/dev/null &
compton &>/dev/null &
dunst &>/dev/null &

xrdb -merge ~/.Xresources &>/dev/null &
tmux source-file ~/.tmux.conf &>/dev/null &

# Reload colors, fonts, etc.
for pts in /dev/pts/*; do
	(echo -n "$(use-xresources < ~/.Xresources)" > $pts) 2>/dev/null &
done &

# GTK
oomox whizkers &>/dev/null && gtkrc-reload &>/dev/null &

# Chrome
make-chrome-theme-images &>/dev/null &

