#!/usr/bin/env bash
# Uses settings from "screencast"

ffmpeg -i "$1" -vf scale=-1:${3:=900} -c:v libvpx -qmin 1 -qmax 10 \
	-an -threads 0 -slices 8 -auto-alt-ref 1 -lag-in-frames 16 \
	-f webm "$2"
