#!/usr/bin/env bash
# Uses settings from "screencast"

usage() {
	echo "USAGE: resize-video [src] [dest] (height) (qmax)"
  exit 1
}

# Sanity checks
[ "$#" -lt 2 ] && usage

ffmpeg -i "$1" -vf scale=-1:${3:=900} -c:v libvpx -qmin 1 -qmax ${4:=10} \
	-an -threads 0 -slices 8 -auto-alt-ref 1 -lag-in-frames 16 \
	-f webm "$2"
