#!/usr/bin/env bash
# Downloads a SoundCloud track, then applies these id3 tags:
#   Title
#   Artist
#   Art
#
# Dependencies: curl, grep, jq
#
# Required environment variables:
#   $SC_CLIENT: SoundCloud API client ID.
#
# Author: metakirby5

checkdep() {
  which "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep curl)$(checkdep grep)$(checkdep jq)"
if [ "$missing" ]; then
  echo "The following dependencies are missing:$missing"
  exit 1
fi

usage() {
  echo "Usage: $(basename "$0") [SoundCloud url]"
  exit 1
}

# Complain if incorrect args.
[ "$#" -ne 1 ] && usage

maybe_exit() {
  if [ -z "$1" ]; then
    echo "$2"
    exit "${3:-1}"
  fi
}

echo 'Fetching song data...'
data="$(curl -sfg "$1" |
  grep -o 'c=\[.*\],' | grep -o '\[.*\]' |
  jq -r '.[4].data[0]')"
maybe_exit "$data" 'Failed to pull data from url.'

echo 'Fetching song...'

# Fetch the mp3 url
mp3_data="$(curl -sfg \
  "https://api.soundcloud.com/i1/tracks/$( \
  <<<"$data" jq -r '.id')/streams?client_id=$SC_CLIENT")"
maybe_exit "$mp3_data" 'Failed to get mp3 url from SoundCloud.'

# Then fetch the mp3
mp3_file="$(<<<"$data" jq -r '"\(.user.username) - \(.title)"').mp3"
curl -g -o "$mp3_file" "$(<<<"$mp3_data" jq -r '.http_mp3_128_url')"

echo 'Fetching image...'
img_url="$(<<<"$data" jq -r '.artwork_url' | sed 's/-large/-t500x500/')"
img_file="$(mktemp).${img_url##*.}"
curl -g -o "$img_file" "$img_url"

echo 'Writing tags...'
eyeD3 "$mp3_file" \
  -t "$(<<<"$data" jq -r '.title')" \
  -a "$(<<<"$data" jq -r '.user.username')" \
  --add-image "$img_file:FRONT_COVER"

# Clean up.
rm "$img_file"
