#!/bin/bash

if [[ $# < 2 ]]; then
	echo
	echo "Vimdiffs assignments if differences exist."
	echo "Usage: tester [local prog] [solution prog] [args]"
	echo
	exit 1
fi

testdir=tester_files

if [[ ! -d $testdir ]]; then
	mkdir $testdir
fi

loc=$1
shift
soln=$1
shift

while [[ $# > 0 ]]; do
	args="$args $1"
	shift
done

$loc$args >& $testdir/local.out
$soln$args >& $testdir/solution.out

cd $testdir
if [[ $(diff local.out solution.out) ]]; then
	echo
	echo "!!! DIFFERENCE FOUND FOR $loc$args"
	diff local.out solution.out
else
	echo
	echo "No differences for $loc$args"
fi
