#!/bin/bash

if [[ $# < 3 ]]; then
	echo
	echo "Vimdiffs assignments if differences exist."
	echo "Usage: tester [input] [local prog] [solution prog] [args]"
	echo
	exit 1
fi

testdir=tester_files

if [[ ! -d $testdir ]]; then
	mkdir $testdir
fi

input=$1
shift
loc=$1
shift
soln=$1
shift

while [[ $# > 0 ]]; do
	args="$args $1"
	shift
done

cat $input | $loc$args >& $testdir/local.out
cat $input | $soln$args >& $testdir/solution.out

cd $testdir
if [[ $(diff local.out solution.out) ]]; then
	echo
	echo "!!! DIFFERENCE FOUND FOR cat $input | $loc$args"
	diff local.out solution.out
else
	echo
	echo "No differences for cat $input | $loc$args"
fi
