#!/usr/bin/env bash

# todo-head
# Author: Ethan Chan
# Date: 2/6/14
#
# A script to echo the first line of my todo list, if any tasks exist.
# Otherwise, a smiley is echoed.

if [[ $(cat ~/todo.txt) ]]; then head -n1 ~/todo.txt; else echo "☺"; fi

# ☺
