#!/bin/bash

# update-gitignore
# Author: ???
# Date: ???
#
# A command to update the .gitignore with all currently untracked files.

if [[ ! -f ".gitignore" ]]; then
    touch .gitignore
fi

git status --porcelain | grep '^??' | cut -c4- >> .gitignore
