#!/bin/bash

# update-configs
# Author: Ethan Chan
# Date: 5/5/14
#
# A script to update my git-maintained configs.

echo

echo "===Updating ~/bin..."
cd ~/bin
git pull
echo

echo "===Updating ~/dotfiles..."
cd ~/dotfiles
git pull
echo
