#!/usr/bin/env bash
# Halves video dimensions for uploading to GitLab.
#
# Dependencies: ffmpeg
#
# Author: metakirby5

checkdep() {
  type "$1" &>/dev/null || echo " $1"
}

missing="$(checkdep ffmpeg)"
if [ "$missing" ]; then
  echo "The following dependencies are missing:$missing"
  exit 1
fi

usage() {
  echo "Usage: $(basename "$0") [filename] (new height)"
  exit 1
}

[ "$#" -lt 1 ] && usage

out="$(mktemp).${1##*.}"
ffmpeg -i "$1" -max_muxing_queue_size 4000 \
  -vf "scale=trunc(oh*a/2)*2:${2:-ih/2}" "$out" &&
  mv "$out" "$1" ||
  rm "$out"
