#!/usr/bin/env bash

# wchat
# Author: Ethan Chan
# Date: 5/4/14
#
# A script to emulate a multi-person chatroom using write.

usage() {
	echo "Usage: wchat [your name] [user1 (pts/XXX)] (user2 (pts/XXX)) (...)"
	echo
}

echo

if [[ $# -eq 0 ]]; then
	usage
	echo "    Sets up multi-way write with timestamp and handle."
	echo "    See available users using:"
	echo "        $ finger"
	echo
	exit 0
fi

if [[ $# -lt 2 ]]; then
	echo "ERROR: Missing recipients!"
	error=1
fi

handle=$1
shift

# Process additional args
while [[ $# -gt 0 ]]; do

	# Process tty
	if [[ $1 =~ ^pts/ ]]; then
		rmtail=${people%%)}
		person=${rmtail##* }

		# Is there even a person to give the tty?
		if [[ $person ]]; then

			# Is that person online?
			if [[ $(finger | grep ^$person | grep $1) ]]; then
				people="$rmtail $1)"
			else
				# What kind of mistake did the user make?
				if [[ $person =~ ^pts/ ]]; then
					rmhead=${people##*write }
					realperson=${rmhead%%[ )]*}
					echo "ERROR: multiple tty per user not supported!"
					echo "       Context: $realperson $person $1"
				else
					echo "ERROR: tty $1 not found for user $person!"
				fi
				error=1
			fi
		else
			echo "ERROR: No user to assign tty $1 to!"
			error=1
		fi

	# Process user
	else
		if [[ $(finger | grep ^$1) ]]; then
			people="$people >(write $1)"	# For tee-ing
			HRPeople="$HRPeople $1"			# Human-readable version
		else
			echo "ERROR: User $1 not found!"
			error=1
		fi
	fi
	shift
done

if [[ $error ]]; then
	echo
	echo "Error(s) encountered, aborting..."
	echo
	usage
	exit $error
fi

mesg y  # Turn on messages
echo "====================Now chatting!===================="
echo "Chatting with:$HRPeople"

# Eval because process substitution is stupid. Need to use fflsuh with awk
# so the messages come through instantly, rather than at EOF.
eval "cat | awk '{ \
	print ((NR == 1) ?\"\nSender: $USER\nRecipients:$HRPeople\n\n\" : \"\n\"), \
	strftime(\"[%H:%M:%S]\"), \"$handle: \" \$0;\
	fflush();\
}' | tee$people > /dev/null"
