#!/bin/bash

# chat
# Author: Ethan Chan
# Date: 5/4/14
#
# A script to emulate a multi-person chatroom using write.

echo

if [[ $# == 0 ]]; then
	echo "Sets up multi-way write with timestamp and handle."
	echo "See available users using \"$ finger\"."
	echo "Usage: chat [your name] [user1 [pts/XXX]] [user2 [pts/XXX]] [...]"
	echo
	exit 1
fi

if [[ $# < 2 ]]; then
	echo "ERROR: Missing recipients!"
	error=1
fi

handle=$1
shift

# Process additional args
while [[ $# > 0 ]]; do

	# Process pts
	if [[ $1 =~ ^pts/ ]]; then
		rmtail=${people%%)}
		person=${rmtail##* }
		if [[ $(finger | grep ^$person | grep $1) ]]; then
			people="$rmtail $1)"
		else
			if [[ $person =~ ^pts/ ]]; then
				rmhead=${people##*write }
				realperson=${rmhead%%[ )]*}
				echo "ERROR: multiple tty per user not supported!"
				echo "       Context: $realperson $person $1"
			else
				echo "ERROR: tty $1 not found for user $person!"
			fi
			error=1
		fi
	# Process user
	else
		if [[ $(finger | grep ^$1) ]]; then
			people="$people >(write $1)"
		else
			echo "ERROR: User $1 not found!"
			error=1
		fi
	fi
	shift
done

if [[ $error ]]; then
	echo
	echo "Error(s) encountered, aborting..."
	echo
	exit $error
fi

echo "Now chatting!"

# Eval because process substitution is stupid. Need to use fflsuh with awk
# so the messages come through instantly, rather than at EOF.
eval "cat | awk '{ print \"\n\", strftime(\"[%H:%M:%S]\"), \"$handle: \" \$0, \
	\"\n[typing...]\"; fflush(); }' | tee$people > /dev/null"
