#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "This is a weird tree."
else
  echo "     _              __"
  echo "    / \`\\  (~._    ./  )"
  echo "    \\__/ __\`-_\\__/ ./"
  echo "   _ \\ \\/  \\   \\ |_    __"
  echo " (   )  \\__/ -^    \\  /  \\"
  echo "  \\_/ \"  \\  | o  o  | .. / __"
  echo "       \\\\. -' ====  /  || /  \\ "
  echo "         \\   .  .  |---__.\\__/"
  echo "         /  :     /   |   |"
  echo "         /   :   /     \\_/"
  echo "      --/ ::    ("
  echo "     (  |     (  (____"
  echo "   .--  .. ----**.____)"
  echo "   \\___/          "
  echo
fi

