#!/usr/bin/env bash
# Runs whizkers with environment variable support, asks for a theme using
# dmenu, and reloads the desktop.

yes 2>/dev/null | relink-config >/dev/null

if [ "$?" -ne 0 ]; then
  echo 'relink-config FAILED'
  exit 1
fi

if [ "$#" -eq 0 ]; then
  selected=$(whizkers -l |\
    dmenu -i -f -fn "Calibri:pixelsize=28" -sb "#3f91c0" -b -h 100 -t \
    -p 'Whizkers Scheme')
  [ -z "$selected" ] && exit 0
  whizkers -e $selected
else
  whizkers -e "$@"
fi

[ "$?" -ne 0 ] && exit 1

killall compton &>/dev/null
killall conky &>/dev/null
killall dunst &>/dev/null
killall lemonbar &>/dev/null
i3-msg 'restart' &>/dev/null

sleep 0.5

xrdb ~/.Xresources &>/dev/null &
compton &>/dev/null &
dunst &>/dev/null &
~/.config/lemonbar/emit 2>/dev/null |\
  lemonbar -u 2 -f "M+ 1p-7" |\
  sh &>/dev/null &

exit 0

